language: go
go:
  - "1.10"

install:
  - go get -d -v github.com/gojibjib/gopeana

script:
  - go test -v github.com/gojibjib/gopeana

env:
  global:
    - secure: "I9Nod5bOa9/bkd852VQAev9uetnUZbORV0VwNnxgz0pg9RMguauBO/u4DE6hFKJKEWFCC8xnCSERgTzy7pUVpXFcZaG3Ckel31rkeiuNZGyDfI7BDSKz2sGvnwSvZeoSwoQAkwBYayhPupjWUy+wlEcbrWekLYq4CATxyE/ZjsGt0VFtlaf0oGn1rrkMMJTEs3KB/1+9uZv2V8yrmIIXBhldKdbByZEzRsVRF2Zqd4QFHFjV+djWBAnKjlEw8f5jeNDiGrQS7tIKFsuFcuQMeItiW0vNLFKom+UAzboW8NByWnKhaJWbvkm1yVjpkCSk3kBR/p9v8ZUBL8yDusu7g741hXkP+OyNHGNfa3FY+MAN5kQGeprj0UwwgU6zUTOfchDMkaGorF+Eueup4DWC1LI0OgWkULutenttB0pjtd6ZSp+KP9lnV0vxLE3osvwB17euE1/G5LTaFOKVaboEysYEDv+9dhqMD4U9CbNgbTcwABeYOl+SvvIxXkXNvBRC0hbEmE+SV11SGHGK4Dtc/ummoS2vu/aDNNcYpPctNy09Smn+ARRtn4HqEp54yxndLYuTDdyE1Z1u7Tc3tzPhrmC3AqXpKmnNNGy3LYpxrydM4aPUaF+GsOwmIvAR0CL8HC12erWPWB9GMWyXWYABpcgFj80/G4/hnPLKPLAPM7I="
